vich_uploader:
    db_driver: orm

    mappings:
        ads_image:
            uri_prefix: /images/annonces
            upload_destination: '%kernel.project_dir%/public/images/annonces'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        users_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
