home:
    path: /
    controller: App\Controller\HomeController::home

ads:
    path: /ads
    controller: App\Controller\AdController::index

ads_show:
    path: /ads/{slug}-{id}
    controller: App\Controller\AdController::show
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'