home:
    path: /
    controller: App\Controller\HomeController::home

hello:
    path: /hello/{prenom}
    controller: App\Controller\HomeController::hello
    defaults:
        prenom: ' Ã  vous'
    requirements:
        prenom: .+

#hello_bis:
#    path: /hello
#    controller: App\Controller\HomeController::hello