home:
    path: /
    controller: App\Controller\HomeController::home

user_show:
    path: /user/{slug}
    controller: App\Controller\UserController::index
    requirements:
        slug: '[a-z0-9\-]+'

account_login:
    path: /login
    controller: App\Controller\AccountController:login

account_logout:
    path: /logout
    controller: App\Controller\AccountController:logout

account_account:
    path: /account
    controller: App\Controller\AccountController:myAccount

account_register:
    path: /register
    controller: App\Controller\AccountController:register

account_profile:
    path: /account/profile
    controller: App\Controller\AccountController:profile

account_password:
    path: /account/password-update
    controller: App\Controller\AccountController:updatePassword

account_booking_list:
    path: /account/bookings-list
    controller: App\Controller\AccountController::bookingsList

ads:
    path: /ads
    controller: App\Controller\AdController::index

ads_create:
    path: /ads/new
    controller: App\Controller\AdController::create

ads_show:
    path: /ads/{slug}-{id}
    controller: App\Controller\AdController::show
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

ads_edit:
    path: /ads/{slug}-{id}/edit
    controller: App\Controller\AdController::edit
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

ads_delete:
    path: /ads/{slug}-{id}/delete
    controller: App\Controller\AdController::delete
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

booking_create:
    path: /booking/{slug}-{id}/book
    controller: App\Controller\BookingController::book
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

booking_show:
    path: /booking/{id}
    controller: App\Controller\BookingController::show
    requirements:
        id: '\d+'

admin_account_login:
    path: /admin/login
    controller: App\Controller\Admin\AdminAccountController::login

admin_account_logout:
    path: /admin/logout
    controller: App\Controller\Admin\AdminAccountController::logout

admin_ads:
    path: /admin/ads/{page?1}
    controller: App\Controller\Admin\AdminAdController::index
    requirements:
        page: '\d+'

admin_ads_edit:
    path: /admin/ads/{slug}-{id}/edit
    controller: App\Controller\Admin\AdminAdController::edit
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

admin_ads_delete:
    path: /admin/ads/{slug}-{id}/delete
    controller: App\Controller\Admin\AdminAdController::delete
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

admin_comments:
    path: /admin/comments/{page?1}
    controller: App\Controller\Admin\AdminCommentController::index
    requirements:
        page: '\d+'

admin_comments_edit:
    path: /admin/comment/{id}/edit
    controller: App\Controller\Admin\AdminCommentController::edit
    requirements:
        id: '\d+'

admin_comments_delete:
    path: /admin/comments/{id}/delete
    controller: App\Controller\Admin\AdminCommentController::delete
    requirements:
        id: '\d+'

admin_bookings:
    path: /admin/bookings/{page?1}
    controller: App\Controller\Admin\AdminBookingController::index
    requirements:
        page: '\d+'

admin_bookings_edit:
    path: admin/bookings/{id}/edit
    controller: App\Controller\Admin\AdminBookingController::edit
    requirements:
        id: '\d+'

admin_bookings_delete:
    path: /admin/bookings/{id}/delete
    controller: App\Controller\Admin\AdminBookingController::delete
    requirements:
        id: '\d+'
