home:
    path: /
    controller: App\Controller\HomeController::home

account_login:
    path: /login
    controller: App\Controller\AccountController:login

account_logout:
    path: /logout
    controller: App\Controller\AccountController:logout

account_register:
    path: /register
    controller: App\Controller\AccountController:register

ads:
    path: /ads
    controller: App\Controller\AdController::index

ads_create:
    path: /ads/new
    controller: App\Controller\AdController::create

ads_show:
    path: /ads/{slug}-{id}
    controller: App\Controller\AdController::show
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'

ads_edit:
    path: /ads/{slug}-{id}/edit
    controller: App\Controller\AdController::edit
    requirements:
        slug: '[a-z0-9\-]+'
        id: '\d+'